#+TITLE: Emacs on Windows外部程序调用
#+AUTHOR: Zhixing
#+STARTUP: showall

* 目录                                                      :TOC:
 - [[#程序调用][程序调用]]
 - [[#gnupg][GnuPG]]
 - [[#git][Git]]
 - [[#texlive][TexLive]]

* 程序调用
=Emacs= 在 =Windows= 上使用时要不可避免的调用外部程序，一般情况下是要把可执行文件的路
径加入到 =exec-path= 里面即可。如：
#+BEGIN_SRC emacs lisp
(add-to-list 'exec-path "path/to/program/")
#+END_SRC

但是，对某些程序来说，上面的方法没有产生应有的效果。 winterTTr 提供了
一个比较省事的方法: [[http://www.voidcn.com/blog/winterttr/article/p-3231165.html][emacs调用外部命令的环境设置]] ，主要原因是外部程序的调
用有时也需要emacs的子进程去调用，所以需要把路径加入到 =PATH= 里面。
把下面的代码加进配置即可。

#+BEGIN_SRC emacs lisp
  (defun wttr/prepend-to-exec-path (path)
    "prepand the path to the emacs intenral `exec-path' and \"PATH\" env variable.
Return the updated `exec-path'"
    (setenv "PATH" (concat (expand-file-name path)
                           path-separator
                           (getenv "PATH")))
    (setq exec-path
          (cons (expand-file-name path)
                exec-path)))

  (mapc #'wttr/prepend-to-exec-path
        (reverse ( list
        ;; your path to program
        "~/.emacs.d/extra-bin/clang"
        (concat Emacs "program/Aspell/bin/")
           )))
#+END_SRC


* GnuPG
默认：加密时选择加密方法，修改文件后保存时需要重新输入密码（重新加密）。
在 =Windows= 上可以把这个软件做成便携软件直接放在优盘等地方，换电脑时不必重新安装。
官网直接提供了制件便携版的方法。

调用这个程序时，上面的方法没有产生应有的效果，可以使用下面的代码：
#+BEGIN_SRC emacs lisp
(custom-set-variables '(epg-gpg-program "path/to/program/")) 
#+END_SRC


* Git
 =Git= 做为一个轻量、高效的版本控制工具，是 =Emacser= 应该掌握的工具之一。
它的学习也非常简单，官网提供的 =Pro Git中文版= 可以让你在一晚上学会它的使用。
它的初始配置也非常简单，只需要运行 =config= 来设置一下自己的用户名和邮箱就可以了。
我这里要说的是 =Portable Git= 的初始设置。
首先运行 =git-bash.exe= ，直接运行手册上的命令即可：
#+BEGIN_SRC emacs lisp
$ git config --system user.name "yourname"
$ git config --system user.email youremail
#+END_SRC

运行上面的命令之后，配置会自动加在系统配置里面(
=\PortableGit\mingw64\etc\gitconfig=)
这不在重启或者移动到另一个电脑上时发生改变。
如果想在不同的电脑上使用不同的配置，只需要把上面的命令中 =system= 换成 =global= 即可。不
过不建议这么做，因为它会把配置放在电脑上。想分别设置的话可以放在你的 =Repository= 的文件
夹 =.git= 里面。

* TexLive
使用 =LaTeX= 可以非常方便的把 =org= 文件导成 =PDF= 文件。
官网提供了各种安装方法，安装之后把路径加入到上面的代码中即可。

