#+TITLE: Emacs On Windows  新手指南
#+AUTHOR: Zhixing & LdBeth
#+STARTUP: showall

* 目录                                                                  :TOC:
- [[#我对-emacs-的理解][我对 =Emacs= 的理解]]
- [[#网上的优秀资源待补充][网上的优秀资源（待补充）]]
  - [[#一年成为-emacs-高手像神一样使用编辑器-from-陈斌][一年成为 Emacs 高手(像神一样使用编辑器) from 陈斌。]]
  - [[#spacemacs-rocks-from-子龙山人][Spacemacs-rocks from 子龙山人]]
  - [[#emacs-中文论坛][Emacs 中文论坛]]
  - [[#planet-emacsen][Planet Emacsen]]
- [[#必须知道的知识点][必须知道的知识点]]
  - [[#三个命令][三个命令]]
- [[#emacs-on-windows-下载与图片支持][=Emacs on Windows= 下载与图片支持]]
- [[#emacs-on-windows-启动][=Emacs on Windows= 启动]]
- [[#设置-home-目录与-portable-emacs][设置 =HOME= 目录与 =Portable Emacs=]]
- [[#对-emacs-进行简单配置][对 =Emacs= 进行简单配置]]
- [[#安装-package][安装 =package=]]
- [[#使用-aspell-来检查拼写][使用 =Aspell= 来检查拼写]]
- [[#如何使用大牛的配置][如何使用大牛的配置]]
  - [[#如何使用-spacemacs][如何使用 Spacemacs]]
  - [[#如何使用子龙山人的配置][如何使用子龙山人的配置]]
  - [[#如何使用陈斌的配置][如何使用陈斌的配置]]
- [[#编码问题][编码问题]]
  - [[#为不同的程序设置编码][为不同的程序设置编码]]
  - [[#修改编码][修改编码]]
- [[#待补充尽管提意见][待补充（尽管提意见）……]]

* 我对 =Emacs= 的理解
  1. 只要是关于文本的，它就能实现，前提是你会 lisp 语言。
  2. Emacs 对 Windows 的支持是因为它的开发者想让大家体验自由软件，并希望大家可以
     转向 Linux 系统。
  3. 它是一个文本编辑器，只适合做关于文本类的事情，拿它去听音乐、看视频不是一个
     好的选择。尽管 Hack Emacs 是一件有趣的事。
  4. 请读一读[[https://github.com/redguardtoo/mastering-emacs-in-one-year-guide/blob/master/guide-zh.org][一年成为 Emacs 高手(像神一样使用编辑器)]]，坚定信仰。
  5. 待补充……

* 网上的优秀资源（待补充）
** [[https://github.com/redguardtoo/mastering-emacs-in-one-year-guide/blob/master/guide-zh.org][一年成为 Emacs 高手(像神一样使用编辑器)]] from 陈斌。
   这是不得不推荐的资源，因为他讲的真的很好。也包括一些 FAQ。

** [[https://github.com/emacs-china/Spacemacs-rocks][Spacemacs-rocks]] from 子龙山人
   一系列视频 (Season 2)，Emacs 入门&专业配置都讲的很好。

** [[https://emacs-china.org/][Emacs 中文论坛]]
   可能是最好的中文论坛。

** [[http://planet.emacsen.org][Planet Emacsen]]
   学习 Lisp 有成以后可以来这里找些小众技巧，锻练英语阅读。

* 必须知道的知识点
** 三个命令
M-x describe-variable, 快捷键 C-h v, =查看变量=
M-x describe-function, 快捷键 C-h f, =查看命令=
M-x describe-key,      快捷键 C-h k, =查看快捷键=
上面的三个命令配合Smex来使用可以让你快速了解你想知道的事情。Smex可以在你不知道整
个命令或者函数名的时候进行模糊搜索。

* =Emacs on Windows= 下载与图片支持
  直接从[[https://www.gnu.org/software/emacs/][官网]] 下载是比较好的，选择一个临近的站点，直接下载即可。在下载页面都有官
  方的文件说明。官网现在提供Emacs25.1的软件包和支持包：
  =emacs-n-x86_64-w64-mingw32.zip (64 bit)= and =emacs-n-i686-w64-mingw32.zip (32
  bit)= 下载后直接解压即可。还有相对应的支持包=emacs-n-x-deps.zip= , 把里面的文件复
  制进上面解压后的文件夹里，直接提供了图片的 dll 文件支持。在前面的版本(如
  Emacs24.5)里，下载后的软件里 =\share\emacs\24.5\= 文件夹下的README文件里可以找到
  支持图片的dll文件下载地址。

* =Emacs on Windows= 启动
  解压后的文件里有四个文件夹：bin，libexec，share，var。直接运行 bin 文件夹里的
  =runemacs.exe= 即可。如果没有用过 Emacs, 请运行快捷键 ~Ctrl-h t~ ，查看 Emacs 自
  带的文档，很短，很实用。需要说明的是，Emacs 运行时有一个 Home 目录，它存放你的
  Emacs 配置，比如快捷键设定、主题设定、package（可以理解为插件）下载之类的。查
  看它也很简单， ~C-x C-f~ 后输入 ~/ 回车后看到的目录就是你的 HOME 目录，不过这
  没有必要。在 Windows 平台上建议直接设定 Emacs 的工作目录：
  share/emacs/site-lisp/subdirs.el 里面设定它的工作目录即可。

* 设置 =HOME= 目录与 =Portable Emacs= 
  可以参考[[https://emacs-china.org/t/windows-emacs/797/11][在 windows 平台将 emacs 绿色化的方法]]。
1. 设置HOME目录（需修改Emacs程序内文件）
   新建文件 U:/Emacs/share/emacs/site-lisp/site-start.el
    或者把下面的代码追加到此目录的subdirs.el文件里。

    #+begin_src emacs-lisp
      ;; 设定Emacs程序的HOME路径
      (defvar emacs-home (replace-regexp-in-string "share.*/$" "HOME/" data-directory :from-end)) 
      (unless (file-exists-p emacs-home)
          (make-directory emacs-home :parents))
      ;; 设定$HOME
      (setenv "HOME" (concat emacs-home))
    #+end_src
    或者可以这样做：
    #+begin_src emacs-lisp
      ;; 可以直接获取优盘的盘符U:/ 设定为变量 disk
      (defvar disk (concat (substring data-directory 0 3)))
      (setenv "HOME" (concat disk "Home/"))
      ;; 上面的 home 和 home-spacemacs 用来存放两份不同的配置。
    #+end_src

2. 还有一种方法也可以实现 *Emacs* 的绿色化，而且不用修改 *Emacs* 的原文件。
   1) 新建文件 *.emacs*
      文件位置可以自己定。写入下面的代码：
      #+BEGIN_SRC emacs-lisp
        ;; 获取优盘的盘符，并设置home路径
        (defvar emacs-home (concat (substring data-directory 0 3) "HOME/"))
        ;; 创建目录
        (unless (file-exists-p emacs-home)
            (make-directory emacs-home :parents))
        ;; 设置$HOME目录：如 g:/Home/
        (setenv "HOME" (concat emacs-home))
        (load-file "~/.emacs.d/init.el")
      #+END_SRC

   2) 新建 *emacs.bat* 文件。
      #+BEGIN_SRC shell
      runemacs.exe -l g:/.emacs
      #+END_SRC
      上面的 *runemacs.exe* 和 *.emacs* 分别替换成相应的路径即可。

   3) 双击 *bat* 文件运行即可。

* 对 =Emacs= 进行简单配置
  HOME 目录怎么存放配置呢？打开 Emacs， ~C-x C-f~ 输入 =~/.emacs.d/init.el= 或者
  =~/.emacs= 提示是否要新建文件，yes 就可以了（我主要用 init.el，后面提到配置文件
  也是指这个文件，这两个文件没有区别）。然后输入配置（举例）：

  #+begin_src emacs-lisp
  ;; 开启行号
  (global-linum-mode 1)
  #+end_src

  输入之后在代码末尾 ~C-x C-e~ ，可以立即开启行号。或者， ~M-x eval-buffer~ 也可以。
  以后你的配置都可以这样做，如果没有效果，请重启试试。

* 安装 =package=
  要想让 Emacs 可以高效的工作，可以 DIY（通过编辑 init.el），也可以站在巨人的肩
  膀上（安装 package）。已经有许多人写了各种各样的 package，你可以安装它，来使得
  Emacs 更加好用。[[http://www.melpa.org/][Melpa]] 上列了许多 package，每个 package 都有简单的说明和源代码
  链接。找到需要的 package，然后安装即可。

  把下面的代码放进你的配置(init.el)里。有的时候 package 下载的时候需要翻墙的，这
  里使用的是子龙山人做的镜像，体验会更好。
  #+begin_src emacs-lisp
  (require 'package)
  (setq package-archives '(("gnu"   . "http://elpa.emacs-china.org/gnu/")
                           ("melpa" . "http://elpa.emacs-china.org/melpa/")))
  (package-initialize)
  #+end_src
  重启 Emacs，运行命令： ~M-x package-list-package~; ~M-x package-refresh-contents~;
  ~C-s NAME~ （你需要安装的 package 名字），找到后用鼠标点击，安装即可。
  或者 ~M-x package-install RET NAME(package) RET~

  还有一种方法比较新颖，也很方便：使用 use-package（也是一个 package）
  在上面的代码后面加上如下代码即可：

  #+begin_src emacs-lisp
    ;; Install use-package
    (unless (package-installed-p 'use-package)
      (package-refresh-contents)
      (package-install 'use-package))
    ;; Automatically install package, such as cnfonts
    (use-package cnfonts
      :config
      (cnfonts-enable)
      (add-hook 'after-make-frame-functions #'cnfonts-set-font-with-saved-step)
    #+end_src
  建议每个人都安装这个 package，或者通过网络上的其它方法来设置中英文字体，否则
  Emacs 会很卡。

* 使用 =Aspell= 来检查拼写
  在 Windows 平台，可以使用 Aspell 等程序来实现对 Emacs 中 org 文件内容检查拼写。
  配置也很简单，而且依然可以便携，因为安装好的 Aspell 程序是便携的（可以直接拷贝
  它的安装文件，放在优盘里），Emacs 只要调用它就可以了。我会把我使用的 Aspell 程
  序压缩后放在群文件里。安装 =flyspell-correct= 后，添加下面的代码即可：
  #+begin_src emacs-lisp
    (add-to-list 'exec-path "~/Aspell/bin/")
    (setq ispell-program-name "aspell")
    (use-package flyspell-correct-ido
      :config
      (require 'flyspell-correct-ido)
      (setq flyspell-correct-interface #'flyspell-correct-ido))
  #+end_src
  具体 flyspell-correct 的使用见它的 README

* 如何使用大牛的配置
  强烈推荐使用 [[https://github.com/redguardtoo/emacs.d][陈斌的配置]] 或者是  [[https://github.com/syl20bnr/spacemacs/tree/develop][Spacemacs]] 。 [[https://github.com/zilongshanren/spacemacs-private][子龙山人的配置]] 是私人定制的，使用
  Spacemacs 的用户建议把他的配置下载下来看看代码，会对自己配置 Spacemacs 有很好
  的借鉴。

** 如何使用 [[http://spacemacs.org][Spacemacs]]
   直接下载 [[https://github.com/syl20bnr/spacemacs/tree/develop][Spacemacs]] 的 [[https://github.com/syl20bnr/spacemacs/archive/develop.zip][Zip]] 文件，然后放到 HOME/.emacs.d/下面即可。按照说明进行
   操作即可。如果出现错误可能是墙的原因，请添加下面的代码到 HOME 目录下.spacemacs
   文件里=dotspacemacs/user-init= 部分

   #+begin_src emacs-lisp
   (setq configuration-layer--elpa-archives
         '(("melpa-cn" . "http://elpa.emacs-china.org/melpa/")
           ("org-cn"   . "http://elpa.emacs-china.org/org/")
           ("gnu-cn"   . "http://elpa.emacs-china.org/gnu/")))
   #+end_src
   然后重启。

   详见 [[http://spacemacs.org/doc/FAQ][FAQ]] ([[https://github.com/LdBeth/Emacs-for-Noobs/blob/master/Sapcemacs%2520FAQ.org][中文]])

** 如何使用子龙山人的配置
   直接下载 Spacemacs 的 zip 文件，解压到 HOME/.emacs.d/下面。
   然后下载 [[https://github.com/zilongshanren/spacemacs-private][子龙山人]] 的 [[https://github.com/zilongshanren/spacemacs-private/archive/develop.zip][配置文件]] ，解压到 HOME/.spacemacs.d/下面
   然后运行 runemacs.exe。

** 如何使用陈斌的配置
   他的 [[https://github.com/redguardtoo/emacs.d][github]] 上面详细说明了他的配置安装方法。

   安装过程中如果无法安装package，可能是源的问题，需要更改源。
   更改 =~/.emacs.d/lisp/init-elpa.el= 里面设置 *package-archives* 的部分
   把 https://melpa.org/packages/ 换成 http://elpa.emacs-china.org/melpa/
   把 https://stable.melpa.org/packages/ 换成 http://elpa.emacs-china.org/melpa-stable/

* 编码问题
** 为不同的程序设置编码
许多程序是由Linux系统上移植过来的，所以对Windows用户可能并不友好。
常见的编码问题是Emacs中的Eshell和Shell中出现乱码。可以使用下面 =修改编码= 的方法来
解决问题。
如果是rg，pt，git等小程序导致的问题，可以使用论坛上网友提供的一种方法。通过设置
程序的输入输出编码来解决问题。
#+BEGIN_SRC emacs-lisp
  ;; https://emacs-china.org/t/topic/3894/22
  (when (eq system-type 'windows-nt)
    (set-default 'process-coding-system-alist
                 '(("[pP][lL][iI][nN][kK]" gbk-dos . gbk-dos)
                   ("[cC][mM][dD][pP][rR][oO][xX][yY]" gbk-dos . gbk-dos)
                   ("[rR][gG]" utf-8-dos . gbk-dos)
                   ("[pP][tT]" utf-8-dos . gbk-dos)
                   ("[gG][iI][tT]" utf-8-dos . gbk-dos)
                   )))
#+END_SRC

** 修改编码
  Windows 中文系统的编码是 GBK，也就是说新建的文件默认编码是 GBK，这可能会导致
  Emacs 或者其它 Unix 系应用在处理这些文件的时候出现乱码。同时，将 Emacs 中默认
  文件编码设置为 UTF-8 并设置 Unix 风格的换行符，有助于文件能被其它操作系统正常
  处理。
  #+BEGIN_SRC emacs-lisp
    ;; 转自 http://blog.csdn.net/bbeikke/article/details/8629677
    ;; 编码设置 begin
    (set-language-environment 'Chinese-GB)
    ;; default-buffer-file-coding-system 变量在 emacs23.2 之后已被废弃，使用 buffer-file-coding-system 代替
    (set-default buffer-file-coding-system 'utf-8-unix)
    (set-default-coding-systems 'utf-8-unix)
    (setq-default pathname-coding-system 'euc-cn)
    (setq file-name-coding-system 'euc-cn)
    ;; 另外建议按下面的先后顺序来设置中文编码识别方式。
    ;; 重要提示:写在最后一行的，实际上最优先使用; 最前面一行，反而放到最后才识别。
    ;; utf-16le-with-signature 相当于 Windows 下的 Unicode 编码，这里也可写成
    ;; utf-16 (utf-16 实际上还细分为 utf-16le, utf-16be, utf-16le-with-signature 等多种)
    (prefer-coding-system 'cp950)
    (prefer-coding-system 'gb2312)
    (prefer-coding-system 'cp936)
    ;;(prefer-coding-system 'gb18030)
                                            ;(prefer-coding-system 'utf-16le-with-signature)
    (prefer-coding-system 'utf-16)
    ;; 新建文件使用 utf-8-unix 方式
    ;; 如果不写下面两句，只写
    ;; (prefer-coding-system 'utf-8)
    ;; 这一句的话，新建文件以 utf-8 编码，行末结束符平台相关
    (prefer-coding-system 'utf-8-dos)
    (prefer-coding-system 'utf-8-unix)
    ;; 编码设置 end
  #+END_SRC

* 待补充（尽管提意见）……

#+BEGIN_QUOTE
  不过在没有一年的修炼之前 千万不要猜 Emacs 不能做什么... 重点是头脑灵活,既坚信
  Emacs 无所不能，也适当变通 

                               -- 陈斌《一年成为 Emacs 高手》
#+END_QUOTE

