#+TITLE: WanderLust
#+AUTHOR: LdBeth
#+STARTUP: showall

#+begin_quote 
All mail clients suck. -cira, the author of another mail client, mutt
#+end_quote

#+begin_quote 
  但是后来我发现其它 email 程序都有某种我不喜欢的怪毛病。-- 《Mutt 使用指南》
#+end_quote

* 目录                                                                  :TOC:
 - [[#简介][简介]]
 - [[#wanderlust-的特点][WanderLust 的特点]]
   - [[#超强的信件分类功能][超强的信件分类功能]]
   - [[#信件打分排序功能][信件打分排序功能]]
   - [[#几乎任意条件的彩色设置][几乎任意条件的彩色设置]]
   - [[#可以随意绑定热键][可以随意绑定热键]]
   - [[#设置条件挂钩][设置条件挂钩]]
   - [[#批量邮件处理][批量邮件处理]]
   - [[#_任选编辑器_][_任选编辑器_]]
   - [[#高级的-mime-支持][高级的 MIME 支持]]
   - [[#支持-pgp-加密][支持 PGP 加密]]
   - [[#_mutt_-wanderlust-是免费的][_Mutt_ WanderLust 是免费的]]
 - [[#开始][开始]]
 - [[#配置收信方式][配置收信方式]]
 - [[#配置发信方式][配置发信方式]]
 - [[#maildir-设置][MailDir 设置]]
 - [[#关于密码][关于密码]]
 - [[#待续][待续]]

* 简介
  WanderLust 是一个完全用 Emacs Lisp 实现的一个不需要在 Emacs 之外进行配置的邮件客
  户端。难能可贵的是，即使作为和 GNUS 同样的一个单线程应用，IMAP 收信速度仍然碾压
  绝大部分其它客户端。

  和 Mew 一样，这个包最早是由日本人构建的，所以不需要额外配置字体就能正常显示中文。
  同时 WanderLust 也支持 NNTP，MailDir，POP，RSS 等多种协议。

  为了向《Mutt 使用指南》致敬，我在这里列出了一些不错的特性。

* WanderLust 的特点
  WanderLust 具有以下特点：

** 超强的信件分类功能
   这也是和 Mew/Mutt 相似的地方。

** 信件打分排序功能
   令人惊讶的是，和 Mutt 一样，它也有这种功能。

** 几乎任意条件的彩色设置
   是的。

** 可以随意绑定热键
   因为你在用 Emacs！

** 设置条件挂钩
   同样这也仰仗于 Emacs。

** 批量邮件处理
   当然可以了！

** _任选编辑器_
   额，这个好像做不到。不过你用的 Emacs 已经是最好的编辑器（为了防止被打我得加个
   “之一”）了，而且你也可以用 Evil。

** 高级的 MIME 支持
   WangderLust 依赖于用 Emacs Lisp 实现的 MIME，能够很好地处理各种文件。

** 支持 PGP 加密
   我得说 Emacs 本来就支持。

** _Mutt_ WanderLust 是免费的
   听了上面那么多好处之后，还有比这更好的消息吗？
   

* 开始
  好吧，实际上这个插件极度缺少说明，你几乎无法找到任何介绍这个包的中文资料，甚至
  英文资料也几乎仅限于 EmacsWiki 上模糊不清的几段说明。

  但是至少有自带的 Emacs Manual。
  
  因为这个包可以直接在 melpa 上找到，安装部分就略过。唯一值得注意的是因为依赖包
  比较多，可能要重启几次 Emacs 才能保证安装成功。

  然后，和 Mew 一样，记得在 =init.el= 里面加几行：

  #+begin_src emacs-lisp
    (if (boundp 'mail-user-agent)
        (setq mail-user-agent 'wl-user-agent))
    (if (fboundp 'define-mail-user-agent)
        (define-mail-user-agent
          'wl-user-agent
          'wl-user-agent-compose
          'wl-draft-send
          'wl-draft-kill
          'mail-send-hook))
  #+end_src
  

* 配置收信方式
  WanderLust 用 =~/.folders= 来配置收信方式。非常令人无语的是，这个文件是
  unix-rc 格式的。但是不要被吓退，其实这是很容易弄懂的。

  #+begin_src conf-unix
    %INBOX:johndoe/clear@mail.domain.com:993! "收件箱"
    INBOX {
      %INBOX/Family:johndoe/clear@mail.domain.com:993! "家庭"
      %INBOX/Work:johndoe/clear@mail.domain.com:993! "工作"
      Work {
        .inbox "Bug Reports"
      }
    }
  #+end_src
  
  明白了吗？这就是一个邮件列表了，用不同的标记来告诉 WanderLust 到哪里取邮件。这
  甚至比用 Emacs Lisp 配置还要直观，让我想起了 =org-elfeed= 。（说实话我觉得
  elfeed 的中文支持差爆了，甚至还不如那个性能比较低的 newsticker。）具体格式参照
  Manual。

  但是如果你需要马上上手的话，我就用比较常见的 QQ 邮箱举例了。

  #+BEGIN_SRC conf-unix
    %inbox:7XXXXXXX9/login@imap.qq.com:993!  "QQ Mail"
    路径:用户名/验证方式（QQ 邮箱需要设为 login）@服务器:端口!加上感叹号表示要使用 SSL "用于显示的名称，可以不设"
  #+END_SRC

  需要注意的是，用户名用 =john@foxmail.com= 之类的，也就是中间有@符号的，会导致
  无法正确连接到服务器。目前由于我用 =getmail= 凑合的，还没有很好的解决办法。

  生成的邮件列表结构是这样的：

  #+begin_example 
        总邮箱
         |-收件箱（一个实际邮件文件夹）
         `-INBOX（这个则是用来分类的一个文件夹）
           |-家庭
           |-工作
           `-Work
             `-Bug Reports（本地 MailDir）
  #+end_example
  
  你应该可以看出来，通过这种方式很容易就能同时收取多个邮箱。

  下面就是一个相对复杂的范例了（来自 Emacs Wiki）：
  #+begin_src conf-unix
    # -*- conf-unix -*-
    GMAIL{
       %INBOX:myname/clear@imap.gmail.com:993!         "In"
       %[Gmail]/Sent:myname/clear@imap.gmail.com:993!  "Sent"
       %[Gmail]/Draft:myname/clear@imap.gmail.com:993! "Draft"
       %[Gmail]/Trash:myname/clear@imap.gmail.com:993! "Trash"
       %[Gmail]/Spam:myname/clear@imap.gmail.com:993!  "Spam"

       Buy{
          %buy/ebay:myname/clear@imap.gmail.com:993!     "E-bay"
          %buy/records:myname/clear@imap.gmail.com:993!  "Records"
          %buy/books:myname/clear@imap.gmail.com:993!    "Books"
       }

       Friends{
          %friends/work:myname/clear@imap.gmail.com:993!       "work friends"
          %friends/university:myname/clear@imap.gmail.com:993! "university friends"
          %friends/college:myname/clear@imap.gmail.com:993!    "old friends"
          %friends/highschool:myname/clear@imap.gmail.com:993! "very old friends"
       }
    }

    #Note: usernames with "strange" characters (like "@") must be written 
    #like: "myname@company.com". Folders at my work are delimited by dot '.'.
    WORK{
       %INBOX:"myname@company.com"/clear@mail.company.com        "Inbox"
       %INBOX.Sent:"myname@company.com"/clear@mail.company.com   "Sent"
       %INBOX.Drafts:"myname@company.com"/clear@mail.company.com "Draft"
       %INBOX.Trash:"myname@company.com"/clear@mail.company.com  "Trash"

       Projects{
          %INBOX.Project1:"myname@company.com"/clear@mail.company.com "Project 1"
          %INBOX.Project2:"myname@company.com"/clear@mail.company.com "Project 2"
       }
    }

  #+end_src

  虽然其实也可以直接用 WanderLust 的文件夹管理器来设置，但在第一次启动时最好还是
  了解一下如何配置。
  
* 配置发信方式
  下方是一个 SMTP 配置的范例，你应该放在 =.wl= 里。

  #+begin_src emacs-lisp
    (setq wl-smtp-connection-type 'starttls
          wl-smtp-posting-port 587
          wl-smtp-authenticate-type "plain"
          wl-smtp-posting-user "myname"
          wl-smtp-posting-server "smtp.gmail.com"
          wl-local-domain "gmail.com"
          wl-message-id-domain "smtp.gmail.com")



    ;; 更加复杂的多账号设置
    (setq wl-user-mail-address-list (quote ("myname@gmail.com" "myname@company.com")))

    ;;(NOTE: "M-: wl-draft-parent-folder" => %INBOX:myname/clear@imap.gmail.com:993)
    (setq wl-draft-config-alist
          '(((string-match "company.com" wl-draft-parent-folder)
             (template . "work"))
            ((string-match "gmail.com" wl-draft-parent-folder)
             (template . "gmail"))
            ;; automatic for replies
            (reply "\\(To\\|Cc\\|Delivered-To\\): .*company.com.*"
             (template . "work"))
            (reply "\\(To\\|Cc\\|Delivered-To\\): .*gmail.com.*"
             (template . "gmail"))))

    ;;choose template with C-c C-j
    (setq wl-template-alist
          '(("gmail"
             (wl-from . "My Name <myname@gmail.com>")
             (wl-smtp-posting-user . "myname")
             (wl-smtp-posting-server . "smtp.gmail.com")
             (wl-smtp-authenticate-type ."plain")
             (wl-smtp-connection-type . 'starttls)
             (wl-smtp-posting-port . 587)
             (wl-local-domain . "gmail.com")
             (wl-message-id-domain . "smtp.gmail.com"))
            ("work"
             ("Fcc" . "%INBOX.Sent:\"myname@company.com\"/clear@mail.company.com")
             (wl-from . "My Name <myname@company.com>")
             (wl-smtp-posting-user . "myname@company.com")
             (wl-smtp-posting-server . "mail.company.com")
             (wl-local-domain . "mail.company.com"))
             ("From" . wl-from)))
  #+end_src
  
* MailDir 设置
  尽管 WanderLust 是一个 IMAP 客户端，它也支持用 MailDir。而且不像 GNUS 是把邮件
  全部导入到本地文件夹，WanderLust 是直接对 MailDir 进行读写操作，这使得它可以和
  我很喜欢的 CLT 邮件客户端 Mutt 共存。我使用 WanderLust 其中之一的原因也是我至
  今还没找到 Mew 如何使用 MailDir。

* 关于密码
  不像 Mew 那样需要用那种奇怪的方式来使得不用每次进入邮箱都要输入密码，
  WanderLust 支持用 =elmo-passwd-alist-save= 来在第一次登陆输入密码后保存密码。
  密码通常被保存在 =~/.elmo/passwd= 。不用担心安全问题，因为密码当然不是明文，而
  是被加密处理后保存的。

* 待续 
